id: P009528
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:36:34.414230
source_metadata:
  id: bdr:W1KG4865
  title: མཚར་གཏམ
  author: ''
  volumes:
    231ece2336704799b7ca0e80a47f42fa:
      image_group_id: I1KG5029
      title: ''
      volume_number: 1
      total_pages: 270
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
